#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-mia ) && rm -f /etc/uci-defaults/luci-mia
	chmod 755 /etc/init.d/mia >/dev/null 2>&1
	/etc/init.d/mia enable >/dev/null 2>&1
	exit 0
}
