#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
        /etc/ups/check_ups.sh check        
}                 
 
stop() {          
        pidof ups.sh | xargs kill 
}

boot() {
        /etc/ups/check_ups.sh check
}